//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""UI Control"",
            ""id"": ""ff734a1b-c81a-4fbb-a88a-436df7a76107"",
            ""actions"": [
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Button"",
                    ""id"": ""849080ed-0c5d-4c83-8c3f-9d1f415d3ea0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnZoom"",
                    ""type"": ""Button"",
                    ""id"": ""8df92962-3f21-4305-be46-69a6c3f90972"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""8e1640c4-299d-45c5-a8cd-32b8f2ff8686"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrevCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""08d45d31-2fa1-4a4f-8ab1-a65fcb681f62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bd23f38c-1060-4fa9-be3b-fb8126b2d56f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5932c63-9c7b-488d-ab00-98b3384acdea"",
                    ""path"": ""<Keyboard>/#(+)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3464146-8c80-43ed-b232-104d5b9e4fc5"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03ffc88a-5871-43d9-a634-f384d0dd7555"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c67ae06-2d9a-4afc-8e24-903d6dd84e37"",
                    ""path"": ""<Keyboard>/#(-)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3f3c1bd-1e15-4f9f-a998-ee115d04952c"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40edeada-9ce3-482d-a0f7-e0f7f3c5140f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd083603-aaec-4f2f-a373-35b7151e2b4e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38e2a4ec-7ea8-4461-b878-63eac7e08c26"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc4140ec-a888-4883-b29d-3fe3e0dd8f7c"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3bd2aaf-4247-4376-be57-f37146c4565f"",
                    ""path"": ""<Keyboard>/rightCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0a5a68b-8716-466b-b0d6-df900d7294ac"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MovementControl"",
            ""id"": ""3cbb9d48-4192-4e9c-a721-495e54765024"",
            ""actions"": [
                {
                    ""name"": ""GoLeft"",
                    ""type"": ""Button"",
                    ""id"": ""f87d9425-49fb-4b6d-8f50-fdc46e236c0e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GoRight"",
                    ""type"": ""Button"",
                    ""id"": ""50af69d1-8cc4-4383-9387-6c4ba254dfd0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GoUp"",
                    ""type"": ""Button"",
                    ""id"": ""b86e6417-9c9b-40fc-8c9e-def6f65fb79b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GoDown"",
                    ""type"": ""Button"",
                    ""id"": ""e61d4348-2286-467a-8910-26e3e8353dcd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""71b66122-6b85-4644-8e1f-14528cdcca60"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f8560e2-dbf9-4dea-be7e-d5287c0e83e9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a01cc0e3-7cb0-482f-980c-d54e67c5c1a6"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bf93e3c-6c26-4319-bd87-bc82793178af"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65343491-dd47-43f7-b3fc-a5e417983855"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a26a348d-9a81-47c7-a50d-71728f9dea6c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f51c4451-5bf1-4cea-b752-3033a1efe3d6"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb67ee6f-9b90-4931-b1c6-a908e517f5b6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UI Control
        m_UIControl = asset.FindActionMap("UI Control", throwIfNotFound: true);
        m_UIControl_Zoom = m_UIControl.FindAction("Zoom", throwIfNotFound: true);
        m_UIControl_UnZoom = m_UIControl.FindAction("UnZoom", throwIfNotFound: true);
        m_UIControl_NextCharacter = m_UIControl.FindAction("NextCharacter", throwIfNotFound: true);
        m_UIControl_PrevCharacter = m_UIControl.FindAction("PrevCharacter", throwIfNotFound: true);
        // MovementControl
        m_MovementControl = asset.FindActionMap("MovementControl", throwIfNotFound: true);
        m_MovementControl_GoLeft = m_MovementControl.FindAction("GoLeft", throwIfNotFound: true);
        m_MovementControl_GoRight = m_MovementControl.FindAction("GoRight", throwIfNotFound: true);
        m_MovementControl_GoUp = m_MovementControl.FindAction("GoUp", throwIfNotFound: true);
        m_MovementControl_GoDown = m_MovementControl.FindAction("GoDown", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI Control
    private readonly InputActionMap m_UIControl;
    private IUIControlActions m_UIControlActionsCallbackInterface;
    private readonly InputAction m_UIControl_Zoom;
    private readonly InputAction m_UIControl_UnZoom;
    private readonly InputAction m_UIControl_NextCharacter;
    private readonly InputAction m_UIControl_PrevCharacter;
    public struct UIControlActions
    {
        private @PlayerControls m_Wrapper;
        public UIControlActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Zoom => m_Wrapper.m_UIControl_Zoom;
        public InputAction @UnZoom => m_Wrapper.m_UIControl_UnZoom;
        public InputAction @NextCharacter => m_Wrapper.m_UIControl_NextCharacter;
        public InputAction @PrevCharacter => m_Wrapper.m_UIControl_PrevCharacter;
        public InputActionMap Get() { return m_Wrapper.m_UIControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIControlActions set) { return set.Get(); }
        public void SetCallbacks(IUIControlActions instance)
        {
            if (m_Wrapper.m_UIControlActionsCallbackInterface != null)
            {
                @Zoom.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnZoom;
                @UnZoom.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnUnZoom;
                @UnZoom.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnUnZoom;
                @UnZoom.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnUnZoom;
                @NextCharacter.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnNextCharacter;
                @NextCharacter.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnNextCharacter;
                @NextCharacter.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnNextCharacter;
                @PrevCharacter.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnPrevCharacter;
                @PrevCharacter.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnPrevCharacter;
                @PrevCharacter.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnPrevCharacter;
            }
            m_Wrapper.m_UIControlActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @UnZoom.started += instance.OnUnZoom;
                @UnZoom.performed += instance.OnUnZoom;
                @UnZoom.canceled += instance.OnUnZoom;
                @NextCharacter.started += instance.OnNextCharacter;
                @NextCharacter.performed += instance.OnNextCharacter;
                @NextCharacter.canceled += instance.OnNextCharacter;
                @PrevCharacter.started += instance.OnPrevCharacter;
                @PrevCharacter.performed += instance.OnPrevCharacter;
                @PrevCharacter.canceled += instance.OnPrevCharacter;
            }
        }
    }
    public UIControlActions @UIControl => new UIControlActions(this);

    // MovementControl
    private readonly InputActionMap m_MovementControl;
    private IMovementControlActions m_MovementControlActionsCallbackInterface;
    private readonly InputAction m_MovementControl_GoLeft;
    private readonly InputAction m_MovementControl_GoRight;
    private readonly InputAction m_MovementControl_GoUp;
    private readonly InputAction m_MovementControl_GoDown;
    public struct MovementControlActions
    {
        private @PlayerControls m_Wrapper;
        public MovementControlActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @GoLeft => m_Wrapper.m_MovementControl_GoLeft;
        public InputAction @GoRight => m_Wrapper.m_MovementControl_GoRight;
        public InputAction @GoUp => m_Wrapper.m_MovementControl_GoUp;
        public InputAction @GoDown => m_Wrapper.m_MovementControl_GoDown;
        public InputActionMap Get() { return m_Wrapper.m_MovementControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementControlActions set) { return set.Get(); }
        public void SetCallbacks(IMovementControlActions instance)
        {
            if (m_Wrapper.m_MovementControlActionsCallbackInterface != null)
            {
                @GoLeft.started -= m_Wrapper.m_MovementControlActionsCallbackInterface.OnGoLeft;
                @GoLeft.performed -= m_Wrapper.m_MovementControlActionsCallbackInterface.OnGoLeft;
                @GoLeft.canceled -= m_Wrapper.m_MovementControlActionsCallbackInterface.OnGoLeft;
                @GoRight.started -= m_Wrapper.m_MovementControlActionsCallbackInterface.OnGoRight;
                @GoRight.performed -= m_Wrapper.m_MovementControlActionsCallbackInterface.OnGoRight;
                @GoRight.canceled -= m_Wrapper.m_MovementControlActionsCallbackInterface.OnGoRight;
                @GoUp.started -= m_Wrapper.m_MovementControlActionsCallbackInterface.OnGoUp;
                @GoUp.performed -= m_Wrapper.m_MovementControlActionsCallbackInterface.OnGoUp;
                @GoUp.canceled -= m_Wrapper.m_MovementControlActionsCallbackInterface.OnGoUp;
                @GoDown.started -= m_Wrapper.m_MovementControlActionsCallbackInterface.OnGoDown;
                @GoDown.performed -= m_Wrapper.m_MovementControlActionsCallbackInterface.OnGoDown;
                @GoDown.canceled -= m_Wrapper.m_MovementControlActionsCallbackInterface.OnGoDown;
            }
            m_Wrapper.m_MovementControlActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GoLeft.started += instance.OnGoLeft;
                @GoLeft.performed += instance.OnGoLeft;
                @GoLeft.canceled += instance.OnGoLeft;
                @GoRight.started += instance.OnGoRight;
                @GoRight.performed += instance.OnGoRight;
                @GoRight.canceled += instance.OnGoRight;
                @GoUp.started += instance.OnGoUp;
                @GoUp.performed += instance.OnGoUp;
                @GoUp.canceled += instance.OnGoUp;
                @GoDown.started += instance.OnGoDown;
                @GoDown.performed += instance.OnGoDown;
                @GoDown.canceled += instance.OnGoDown;
            }
        }
    }
    public MovementControlActions @MovementControl => new MovementControlActions(this);
    public interface IUIControlActions
    {
        void OnZoom(InputAction.CallbackContext context);
        void OnUnZoom(InputAction.CallbackContext context);
        void OnNextCharacter(InputAction.CallbackContext context);
        void OnPrevCharacter(InputAction.CallbackContext context);
    }
    public interface IMovementControlActions
    {
        void OnGoLeft(InputAction.CallbackContext context);
        void OnGoRight(InputAction.CallbackContext context);
        void OnGoUp(InputAction.CallbackContext context);
        void OnGoDown(InputAction.CallbackContext context);
    }
}
